---
- hosts: all
  become: true
  
  tasks:
  - name: Update all packages
    yum:
      name: '*'
      state: latest
      update_only: yes
  
  - name: Install amazon linux extras
    yum:
      name: amazon-linux-extras
      state: latest
      update_cache: yes

  - name: Install Dependencies
    command: amazon-linux-extras install epel -y

  - name: Install stress
    command: yum install stress -y
      